
<% user = ENV.key?("POSTGRESQL_ADMIN_PASSWORD") ? "root" : ENV["POSTGRESQL_USER"] %>
<% password = ENV.key?("POSTGRESQL_ADMIN_PASSWORD") ? ENV["POSTGRESQL_ADMIN_PASSWORD"] : ENV["POSTGRESQL_PASSWORD"] %>
<% db_service = ENV.fetch("DATABASE_SERVICE_NAME","").upcase %>

default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["POSTGRESQL_DATABASE"] %>
  username: <%= user %>
  password: <%= password %>
  host: <%= ENV["#{db_service}_SERVICE_HOST"] %>
  port: <%= ENV["#{db_service}_SERVICE_PORT"] %>
  pool: <%= ENV["POSTGRESQL_MAX_CONNECTIONS"] || 5 %>
  template: template0

production:
  <<: *default

development:
  adapter: postgresql
  encoding: unicode
  database: 'pellectio'
  username: 'pellectio'
  password: 'pellectio'
  host: '127.0.0.1'
  port: 5432
  pool: 5
  
test:
  adapter: postgresql
  encoding: unicode
  database: 'pellectio'
  username: 'pellectio'
  password: 'pellectio'
  host: '127.0.0.1'
  port: 5432
  pool: 5
