shared:
  app_name: 'pellect.io'
  app_description: 'pellect.io'
  admin_user_name: admin
  admin_user_email: admin@example.com
  admin_user_password: changeme
  domain_name: example.com
  base_url: http://localhost:3000
  rails_serve_static_files: <%= ENV["RAILS_SERVE_STATIC_FILES"] %>
  smtp_provider_host: <%= ENV["SMTP_PROVIDER_HOST"] %>
  smtp_provider_domain: <%= ENV["SMTP_PROVIDER_DOMAIN"] %>
  smtp_provider_username: <%= ENV["SMTP_PROVIDER_USERNAME"] %>
  smtp_provider_password: <%= ENV["SMTP_PROVIDER_PASSWORD"] %>

development:
  secret_key_base: da8fc48d6bd04c06d613fc962260718aa32f0bb392558a1b43217a5c5b100dc55af899c4a9910075b4d3c45347871f1bfa948ab3a48860ec5e068e28195f6093

test:
  secret_key_base: 6772e91db7e2a67f2b58243e064bad8b1585e526606c01036819e0679543e20985f9ba3e4df0a7daebbc83ae858c9137ee26321b9bf3f177c5d79bb5c203d3c7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  admin_user_name: <%= ENV["APPLICATION_USER"] %>
  admin_user_email: <%= ENV["APPLICATION_USER_EMAIL"] %>
  admin_user_password: <%= ENV["APPLICATION_USER_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  base_url: <%= ENV["BASE_URL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
